### ISSUE TITLE
Feature Request: Multilingual

### ISSUE THREAD

**Issue by haemeulrich** [ChrisHardie/printable-pdf-newspaper#11]
Would be great to have the built in strings in other languages. Or implement the possibility to translate/change the strings.

**Comment by ChrisHardie** [comment]
My understanding is that the plugin is currently set up for translation per the WordPress guidelines. It looks like there are already translations in German and Spanish available as language packs. So anyone interested in helping to offer additional languages can contribute at 

https://translate.wordpress.org/projects/wp-plugins/printable-pdf-newspaper/

I think the only string in the PDF template that is not using the proper i18n function call is "By" before the author name. I'll fix that in the next release.

Edited to add: the strings in the Select2 JS library and some of the JS interactions also need fixing.
