### ISSUE TITLE
Feature: Post Sort

### ISSUE THREAD

**Issue by Luckycooper** [ChrisHardie/printable-pdf-newspaper#33]
Hi

It would be great if you could sort the pages and posts.

Example: In a travelogue, it doesn't make sense if the latest post comes first. You want to start the journey all over again.

But otherwise cool plugin, greetings Lukas

**Comment by ChrisHardie** [comment]
Hi @Luckycooper - I'm glad you like the plugin.

You can use the `ppn_post_query_args` filter to change how the post query works, including changing the order. Here's an example of what it might look like added to your functions.php file (not tested) to sort by post date ascending:

```
add_filter( 'ppn_post_query_args', function( $query_args ) { $query_args['orderby'] = 'date'; $query_args['order'] = 'ASC'; return $query_args; }, 10, 1 );
```

I hope that helps.
