### ISSUE TITLE
Feature Request: Widget

### ISSUE THREAD

**Issue by fneurieser** [ChrisHardie/printable-pdf-newspaper#39]
Hello Chris,
would it be possible to add a widget for printable-pdf-newsletter so that a reader could select which content he wants to become as pdf?

Regards
Franz-Georg

**Comment by ChrisHardie** [comment]
Hi @fneurieser. This may be possible but I'm not quite sure I understand the use case yet. Could you share some more details about how you think it could work and what the benefit would be? Thank you.

**Comment by ChrisHardie** [comment]
Closing after no response.
